### ISSUE TITLE
Would you be open to share this step into the Bitrise StepLib?

### ISSUE THREAD

**Issue by viktorbenei** [justice3120/bitrise-step-open-vpn#1]
Hey guys 👋 

I was just wondering if there's a reason why you chose not to share this step in the bitrise steplib?

If there's no blocker I'd be happy to help you with sharing it in the library, or if you prefer we could copy this repo and share it ourselves.

Happy building! 😉

**Comment by justice3120** [comment]
Hi @viktorbenei 
I would like to release it to steplib after brushing up a little.

**Comment by viktorbenei** [comment]
Awesome! Let me know if I can help with anything! 😊

**Comment by justice3120** [comment]
Hi @viktorbenei 
My pull requests (https://github.com/bitrise-io/bitrise-steplib/pull/1805) are merged and I think this plugin is open to the public.
So close this Issue. 😄

**Comment by viktorbenei** [comment]
Indeed it's in the StepLib - it also has its own fancy StepLib page at https://www.bitrise.io/integrations/steps/open-vpn 

Thanks for sharing @justice3120 ! 😉
