### ISSUE TITLE
Making your step an Bitrise Maintained Step

### ISSUE THREAD

**Issue by jani-vrancsik** [justice3120/bitrise-step-open-vpn#5]
Hi @justice3120 👋, 

Janos here from the Bitrise partnership team.

I'm reaching out to you as we'd like to take ownership of your community step and make it a Bitrise maintained step.

Considering that there were no updates for the step in a while - and it carries a potential security risk - we'd like to make it an official step instead of a community step.

Just wanted to reach out to you and let you know about. Let me know if you have any issues with the decision or you'd like to contribute to it going forward.

Cheers,
Janos

**Comment by justice3120** [comment]
Hi, @Janos-vrancsik 
Is no problem!

**Comment by dennisrivard** [comment]
@Janos-vrancsik - is this going to happen? What is the timeframe?

**Comment by jani-vrancsik** [comment]
@dennisrivard Yes, it's going to happen. It's getting scheduled for our upcoming sprint. I can't really give an exact timeframe but I'd say in a matter of a few weeks.
